services:
  - type: web
    name: brainstation-api
    env: node
    plan: free
    buildCommand: yarn &&
      yarn run migrate:down &&
      yarn run migrate &&
      yarn run seed
    startCommand: node index.js
